name: app_taxi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  cached_network_image: ^1.0.0
  carousel_pro: ^1.0.0
  rxdart:
  intl: ^0.15.8
  provider: ^3.0.0+1
  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    - assets/images/icon-car.jpg
    - assets/images/bg.png
    - assets/images/logo.png
    - assets/images/ic_car_red.png
    - assets/images/ic_car_green.png
    - assets/images/ic_user.png
    - assets/images/ic_lock.png
    - assets/images/ic_mail.png
    - assets/images/ic_phone.png
    - assets/images/ic_location_black.png
    - assets/images/ic_map_nav.png
    - assets/images/ic_notify.png
    - assets/images/ic_remove_x.png
    - assets/images/ic_menu.png
    - assets/images/ic_menu_help.png
    - assets/images/ic_menu_history.png
    - assets/images/ic_menu_logout.png
    - assets/images/ic_menu_notify.png
    - assets/images/ic_menu_percent.png
    - assets/images/ic_menu_user.png
    - assets/images/ic_pickup_hatchback.png
    - assets/images/ic_pickup_sedan.png
    - assets/images/ic_pickup_suv.png
    - assets/images/ic_pickup_van.png
 
  fonts:
    - family: UTM Avo
      fonts:
        - asset: assets/fonts/UTM Avo.ttf
        - asset: assets/fonts/UTM AvoBold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
